### ISSUE TITLE
Checkbox a11y

### ISSUE THREAD

**Issue by kim366** [tailwindlabs/tailwindcss-custom-forms#81]
Hello, you've done great work on these components! Unfortunately, I see, with many libraries that restyle checkboxes, accessibility suffers, as you can't control the checkbox with the keyboard. Radio buttons work well, which is a lot better than other libraries.

While a checkbox has focus, pressing the space bar should toggle it.

**Comment by adamwathan** [comment]
The space bar does toggle it, it is literally just a regular HTML checkbox:

![checkbox](https://user-images.githubusercontent.com/4323180/97433763-64f81980-18f4-11eb-9d5c-a0b9e40ad0ea.gif)

Try it out here:

https://tailwindcss-custom-forms.netlify.app/

There is no JS or anything fancy here, just some CSS around a regular `<input type="checkbox">` so all of the standard browser behavior just works 👍🏻

**Comment by kim366** [comment]
Hmm, then it must be a bug with my browser, sorry
